[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"

[font]
size = 12.0
normal = { family = "MesloLGS NF" }

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 3
y = 0

[colors.normal]
black   = "#141d2b"
red     = "#ff3e3e"
green   = "#9fef00"
yellow  = "#ffaf00"
blue    = "#0086ff"
magenta = "#9f00ff"
cyan    = "#2ee7b6"
white   = "#a4b1cd"

[colors.primary]
background = "#141d2b"
foreground = "#ffffff"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
